# -*- coding: utf-8 -*-
"""cadastro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rwa_esFSu1JlwQiTT5tP85kXNmj5Au-w
"""

print ("Realização de cadastro")
while True:

  opcao = input("Digite 1 para cadastrar o CPF e 2 pra cadastrar CNPJ:")

  if opcao == "1":
    nome = input("Digite seu nome:")
    cpf = input("Digite seu CPF:")
    email = input("Digite seu email:")
    telefone = input("Digite seu telefone:")
    print("\nCadastro com CPF finalizado.")
    print("\nNome:", nome, "\nCPF:", cpf, "\nEmail:", email, "\nTelefone:", telefone)

  elif opcao == "2":
    nome_empresa = input("Digite o nome da empresa:")
    cnpj = input("Digite seu CNPJ:")
    email = input("Digite seu email:")
    telefone_empresa = input("Digite seu telefone:")
    print("\nCadastro com CPF finalizado.")
    print("\nNome da empresa:", nome_empresa, "\nCNPJ:", cnpj, "\nEmail:", email, "\nTelefone da empresa:", telefone_empresa)

  else:
    print ("\nOpção invalida.")
    continue

  continuar = input("\nDigite 1 para cadastrar outro usuário, ou qualquer digito para finalizar: ")

  if continuar == "1":
    print ("\nIniciando novo cadastro")
  else:
    print ("\nCadastro finalizado.")
    break

